# Generated by Django 2.1.2 on 2019-03-01 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190228_0624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='portfolio_site',
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='bio',
            field=models.CharField(default=None, max_length=120),
        ),
    ]
