# Generated by Django 2.1.2 on 2019-03-01 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190301_0630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='bio',
            field=models.CharField(default='Add bio', max_length=120),
        ),
    ]
