# Generated by Django 2.1.2 on 2019-03-01 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190301_0631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='bio',
            field=models.CharField(blank=True, default='Add bio', max_length=120, null=True),
        ),
    ]
