# Generated by Django 2.1.2 on 2019-03-01 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190301_0649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='bio',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
