# Generated by Django 2.1.2 on 2019-03-01 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190301_0650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='bio',
            field=models.CharField(default='Add bio', max_length=200),
        ),
    ]
