# Generated by Django 2.1.2 on 2019-03-04 09:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20190304_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweets',
            name='user_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.UserProfileInfo'),
        ),
        migrations.AlterField(
            model_name='tweets',
            name='published_time',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2019, 3, 4, 9, 19, 48, 868570)),
        ),
    ]
