# Generated by Django 2.1.2 on 2019-03-04 09:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20190304_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweets',
            name='published_time',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2019, 3, 4, 9, 31, 34, 290358)),
        ),
        migrations.AlterField(
            model_name='tweets',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.UserProfileInfo'),
        ),
    ]
