# Generated by Django 2.1.2 on 2019-03-04 12:24

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0015_auto_20190304_0931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweets',
            name='user',
        ),
        migrations.AddField(
            model_name='tweets',
            name='user_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tweets',
            name='published_time',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2019, 3, 4, 12, 24, 18, 87359)),
        ),
    ]
