# Generated by Django 2.1.2 on 2019-03-04 12:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20190304_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweets',
            name='published_time',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2019, 3, 4, 12, 25, 45, 526820)),
        ),
    ]
