# Generated by Django 2.1.2 on 2019-03-04 13:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20190304_1338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweets',
            old_name='user_info',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='tweets',
            name='published_time',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2019, 3, 4, 13, 39, 14, 706014)),
        ),
    ]
