# Generated by Django 2.1.2 on 2019-03-05 04:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20190305_0438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweets',
            name='published_time',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2019, 3, 5, 4, 45, 5, 422594)),
        ),
    ]
